--- # configuration
duration: 120
classifier: Video/classifier.pkl
music:
  neutral: Music/Instrumentel.mp3
  sadness: Music/Winds_Caress.mp3
  fear: Music/Trouillos.mp3
  anger: Music/Storm.mp3
  happy: Music/Chinese_Umbrellas_Ragtime.mp3
  disgust: Music/Motivation.mp3
  surprise: Music/Rise.mp3
